name: Build PixelOS A16 Ginkgo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Crave Auth
        run: |
          mkdir -p ~/.crave
          echo "${{ secrets.CRAVE_CONF }}" > ~/.crave/crave.conf
          sed -i 's/{/{\n  "project": "PixelOS",/' ~/.crave/crave.conf

      - name: Install Crave CLI
        run: |
          curl -s https://raw.githubusercontent.com/accupara/crave/refs/heads/master/get_crave.sh | bash
          sudo mv crave /usr/local/bin/ || true

      - name: Run Build on Crave
        run: |
          crave run -- "repo init -u https://github.com/PixelOS-AOSP/android_manifest.git -b sixteen --git-lfs --depth 1 && brunch ginkgo"
